---
dist: bionic
language: generic

before_install:
  - scripts/travis.sh

env:
  global:
    - REPOSITORY=osism/ara-web
  matrix:
    - VERSION=latest
    - VERSION=1.0.0

before_script:
  - bash scripts/lint.sh

script:
  - bash scripts/build.sh

deploy:
  - provider: script
    script: bash scripts/push.sh
    skip_cleanup: true
    on:
      branch: master
